name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v6.0.0
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e49802e8e  # v6.0.0
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: make install

      - name: Install dev dependencies
        run: |
          uv pip install ruff pytest pytest-cov

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test

      - name: Run test coverage
        run: make test-coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@aa23f6cecfefec641a3ac137b917b77f163a8432  # v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=julverik_python-project-50
            -Dsonar.organization=julverik
            -Dsonar.python.coverage.reportPaths=coverage.xml