name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install uv
          make install

      - name: Run linter and tests
        run: |
          make lint
          make test

      - name: Run test coverage
        run: |
          make test-coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=julverik_python-project-50
            -Dsonar.organization=julverik
            -Dsonar.python.coverage.reportPaths=coverage.xml